/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppSkillsRouteImport } from './routes/app.skills'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as AppSkillsSkillIdRouteImport } from './routes/app.skills.$skillId'
import { Route as AppTopicsTopicIdRouteImport } from './routes/app.topics.$topicId'
import { Route as AppTopicsNewRouteImport } from './routes/app.topics.new'
import { Route as TopicsSlugRunsRunIdRouteImport } from './routes/topics.$slug_.runs.$runId'
import { Route as AppTopicsTopicIdRunsRunIdRouteImport } from './routes/app.topics.$topicId_.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsSkillIdRoute = AppSkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => AppSkillsRoute,
} as any)
const AppTopicsTopicIdRoute = AppTopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsNewRoute = AppTopicsNewRouteImport.update({
  id: '/topics/new',
  path: '/topics/new',
  getParentRoute: () => AppRoute,
} as any)
const TopicsSlugRunsRunIdRoute = TopicsSlugRunsRunIdRouteImport.update({
  id: '/topics/$slug_/runs/$runId',
  path: '/topics/$slug/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopicsTopicIdRunsRunIdRoute =
  AppTopicsTopicIdRunsRunIdRouteImport.update({
    id: '/topics/$topicId_/runs/$runId',
    path: '/topics/$topicId/runs/$runId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/skills': typeof AppSkillsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/app/topics/$topicId': typeof AppTopicsTopicIdRoute
  '/app/topics/new': typeof AppTopicsNewRoute
  '/topics/$slug/runs/$runId': typeof TopicsSlugRunsRunIdRoute
  '/app/topics/$topicId/runs/$runId': typeof AppTopicsTopicIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/skills': typeof AppSkillsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/app': typeof AppIndexRoute
  '/app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/app/topics/$topicId': typeof AppTopicsTopicIdRoute
  '/app/topics/new': typeof AppTopicsNewRoute
  '/topics/$slug/runs/$runId': typeof TopicsSlugRunsRunIdRoute
  '/app/topics/$topicId/runs/$runId': typeof AppTopicsTopicIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/skills': typeof AppSkillsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/app/topics/$topicId': typeof AppTopicsTopicIdRoute
  '/app/topics/new': typeof AppTopicsNewRoute
  '/topics/$slug_/runs/$runId': typeof TopicsSlugRunsRunIdRoute
  '/app/topics/$topicId_/runs/$runId': typeof AppTopicsTopicIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/inbox'
    | '/app/skills'
    | '/app/subscriptions'
    | '/topics/$slug'
    | '/app/'
    | '/app/skills/$skillId'
    | '/app/topics/$topicId'
    | '/app/topics/new'
    | '/topics/$slug/runs/$runId'
    | '/app/topics/$topicId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/inbox'
    | '/app/skills'
    | '/app/subscriptions'
    | '/topics/$slug'
    | '/app'
    | '/app/skills/$skillId'
    | '/app/topics/$topicId'
    | '/app/topics/new'
    | '/topics/$slug/runs/$runId'
    | '/app/topics/$topicId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/inbox'
    | '/app/skills'
    | '/app/subscriptions'
    | '/topics/$slug'
    | '/app/'
    | '/app/skills/$skillId'
    | '/app/topics/$topicId'
    | '/app/topics/new'
    | '/topics/$slug_/runs/$runId'
    | '/app/topics/$topicId_/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  TopicsSlugRunsRunIdRoute: typeof TopicsSlugRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/skills/$skillId': {
      id: '/app/skills/$skillId'
      path: '/$skillId'
      fullPath: '/app/skills/$skillId'
      preLoaderRoute: typeof AppSkillsSkillIdRouteImport
      parentRoute: typeof AppSkillsRoute
    }
    '/app/topics/$topicId': {
      id: '/app/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/app/topics/$topicId'
      preLoaderRoute: typeof AppTopicsTopicIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/topics/new': {
      id: '/app/topics/new'
      path: '/topics/new'
      fullPath: '/app/topics/new'
      preLoaderRoute: typeof AppTopicsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/topics/$slug_/runs/$runId': {
      id: '/topics/$slug_/runs/$runId'
      path: '/topics/$slug/runs/$runId'
      fullPath: '/topics/$slug/runs/$runId'
      preLoaderRoute: typeof TopicsSlugRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topics/$topicId_/runs/$runId': {
      id: '/app/topics/$topicId_/runs/$runId'
      path: '/topics/$topicId/runs/$runId'
      fullPath: '/app/topics/$topicId/runs/$runId'
      preLoaderRoute: typeof AppTopicsTopicIdRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSkillsRouteChildren {
  AppSkillsSkillIdRoute: typeof AppSkillsSkillIdRoute
}

const AppSkillsRouteChildren: AppSkillsRouteChildren = {
  AppSkillsSkillIdRoute: AppSkillsSkillIdRoute,
}

const AppSkillsRouteWithChildren = AppSkillsRoute._addFileChildren(
  AppSkillsRouteChildren,
)

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppSkillsRoute: typeof AppSkillsRouteWithChildren
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTopicsTopicIdRoute: typeof AppTopicsTopicIdRoute
  AppTopicsNewRoute: typeof AppTopicsNewRoute
  AppTopicsTopicIdRunsRunIdRoute: typeof AppTopicsTopicIdRunsRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppSkillsRoute: AppSkillsRouteWithChildren,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTopicsTopicIdRoute: AppTopicsTopicIdRoute,
  AppTopicsNewRoute: AppTopicsNewRoute,
  AppTopicsTopicIdRunsRunIdRoute: AppTopicsTopicIdRunsRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  TopicsSlugRunsRunIdRoute: TopicsSlugRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
